#!/usr/bin/env python3
"""Assemble ordered proposal sections into the repository's single Markdown output."""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SECTIONS = ROOT / "proposal" / "sections"
DEFAULT_OUTPUT = ROOT / "output" / "proposal.md"
REPO_REFERENCE = re.compile(r"\{\{repo:([^}]+)\}\}")
GENERATED_NOTICE = "<!-- Generated by tools/build_proposal.py. Edit proposal/sections, not this file. -->"


class BuildError(Exception):
    """Raised when proposal inputs violate the repository contract."""


def resolve_repo_reference(raw_path: str, output_dir: Path) -> str:
    reference = Path(raw_path.strip())
    if reference.is_absolute() or ".." in reference.parts:
        raise BuildError(f"Repository reference must stay inside the repository: {raw_path!r}")

    target = (ROOT / reference).resolve()
    try:
        target.relative_to(ROOT)
    except ValueError as exc:
        raise BuildError(f"Repository reference escapes the repository: {raw_path!r}") from exc

    if not target.exists():
        raise BuildError(f"Repository reference does not exist: {raw_path!r}")

    return Path(os.path.relpath(target, output_dir)).as_posix()


def render_section(section_path: Path, output_dir: Path) -> str:
    text = section_path.read_text(encoding="utf-8").strip()
    if not text:
        raise BuildError(f"Section is empty: {section_path.relative_to(ROOT)}")

    def replace(match: re.Match[str]) -> str:
        return resolve_repo_reference(match.group(1), output_dir)

    rendered = REPO_REFERENCE.sub(replace, text)
    if "{{repo:" in rendered:
        raise BuildError(f"Malformed repository reference in {section_path.relative_to(ROOT)}")
    return rendered


def assemble(sections_dir: Path, output_path: Path) -> tuple[str, list[Path]]:
    section_paths = sorted(sections_dir.glob("*/section.md"))
    if not section_paths:
        raise BuildError(f"No section.md files found below {sections_dir}")

    rendered = [render_section(path, output_path.parent) for path in section_paths]
    body = "\n\n---\n\n".join(rendered)
    document = f"{GENERATED_NOTICE}\n\n{body}\n"

    level_one_headings = re.findall(r"(?m)^# [^#].*$", document)
    if len(level_one_headings) != 1:
        raise BuildError(
            "The assembled proposal must contain exactly one level-one heading; "
            f"found {len(level_one_headings)}."
        )

    return document, section_paths


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sections", type=Path, default=DEFAULT_SECTIONS)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit nonzero if the checked-in output differs from a fresh build.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    sections_dir = args.sections.resolve()
    output_path = args.output.resolve()

    try:
        document, section_paths = assemble(sections_dir, output_path)
    except (BuildError, OSError) as exc:
        print(f"proposal build failed: {exc}", file=sys.stderr)
        return 1

    if args.check:
        if not output_path.exists():
            print(f"proposal check failed: missing {output_path.relative_to(ROOT)}", file=sys.stderr)
            return 1
        if output_path.read_text(encoding="utf-8") != document:
            print(
                f"proposal check failed: {output_path.relative_to(ROOT)} is out of date; "
                "run python3 tools/build_proposal.py",
                file=sys.stderr,
            )
            return 1
        print(f"proposal is current ({len(section_paths)} sections)")
        return 0

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(document, encoding="utf-8")
    print(f"built {output_path.relative_to(ROOT)} from {len(section_paths)} sections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

